INSERT INTO books (title, published_year, img) 
VALUES 
('СИ++ И КОМПЬЮТЕРНАЯ ГРАФИКА', 2005, './books-page/books-page_files/22.jpg'), 
('Толковый словарь сетевых терминов и аббревиатур', 2004, './books-page/books-page_files/25.jpg'),
("Програмирование на языке Go!", 2006, "./books-page/books-page_files/23.jpg"),
("Гаррі Поттер і філософський камінь", 2006, "./books-page/books-page_files/test-book.jpg"),
("Володар перснів: Братство персня", 2001, "./books-page/books-page_files/test-book.jpg"),
("Володар перснів: Дві вежі", 2002, "./books-page/books-page_files/test-book.jpg"),
("Володар перснів: Повернення короля", 2003, "./books-page/books-page_files/test-book.jpg"),
("1984", 1998, "./books-page/books-page_files/test-book.jpg"),
("Колгосп тварин", 2000, "./books-page/books-page_files/test-book.jpg"),
("Майстер і Маргарита", 2004, "./books-page/books-page_files/test-book.jpg"),
("Тіні забутих предків", 1985, "./books-page/books-page_files/test-book.jpg"),
("Кобзар", 2010, "./books-page/books-page_files/test-book.jpg"),
("Сто років самотності", 1997, "./books-page/books-page_files/test-book.jpg"),
("Алхімік", 2006, "./books-page/books-page_files/test-book.jpg"),
("Маленький принц", 1995, "./books-page/books-page_files/test-book.jpg"),
("Гра престолів", 2012, "./books-page/books-page_files/test-book.jpg"),
("Битва королів", 2013, "./books-page/books-page_files/test-book.jpg"),
("Буря мечів", 2014, "./books-page/books-page_files/test-book.jpg"),
("Танець драконів", 2016, "./books-page/books-page_files/test-book.jpg"),
("Дюна", 2008, "./books-page/books-page_files/test-book.jpg"),
("451 градус за Фаренгейтом", 1999, "./books-page/books-page_files/test-book.jpg"),
("Автостопом по галактиці", 2007, "./books-page/books-page_files/test-book.jpg"),
("Марсіанин", 2015, "./books-page/books-page_files/test-book.jpg"),
("Темна вежа: Стрілець", 2009, "./books-page/books-page_files/test-book.jpg"),
("Темна вежа: Крізь час", 2010, "./books-page/books-page_files/test-book.jpg"),
("Пісня льоду й полум’я", 2011, "./books-page/books-page_files/test-book.jpg"),
("Шерлок Холмс: Етюд у багряних тонах", 1996, "./books-page/books-page_files/test-book.jpg"),
("Собаче серце", 2003, "./books-page/books-page_files/test-book.jpg"),
("Острів скарбів", 1994, "./books-page/books-page_files/test-book.jpg"),
("Гобіт, або Туди і звідти", 2005, "./books-page/books-page_files/test-book.jpg"),
("Злочин і кара", 1993, "./books-page/books-page_files/test-book.jpg"),
("Мобі Дік", 1992, "./books-page/books-page_files/test-book.jpg"),
("Фундація", 2001, "./books-page/books-page_files/test-book.jpg"),
("Я, робот", 2002, "./books-page/books-page_files/test-book.jpg");